[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "0.0.0"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
major_version_zero = false
version_files = [
    "install.sh:KAKAOTALK_TOOLKIT_VERSION",
]
